services:
  nginx:
    container_name: nginx
    build: nginx/
      #restart: always TODO
    volumes:
      - "~/data/wp:/usr/share/wordpress"
    networks:
      - nginxwordpress
    ports:
      - "443:443"
    depends_on:
      - "wordpress"
  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: wordpress/
      #restart: always TODO
    volumes:
      - "~/data/wp:/usr/share/wordpress"
    networks:
      - nginxwordpress
      - wordpressmariadb
    ports:
      - "9000:9000"
    depends_on:
      - "mariadb"
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: mariadb/
      #restart: always TODO
    volumes:
      - "~/data/db:/var/lib/mysql"
    networks:
      - wordpressmariadb
    ports:
      - "3306:3306"
networks:
  nginxwordpress:
  wordpressmariadb:
