volumes:
  wp:
    name: wp
    driver_opts:
      #type is required by dokcer-compose
      type: none
      # o: bind is to prevent Error response from daemon: failed to mount local volume: mount /home/dnoom/data/db:/var/lib/docker/volumes/db/_data: no such device
      o: bind
      device: /home/dnoom/data/wp
  db:
    name: db
    driver_opts:
      type: none
      o: bind
      device: /home/dnoom/data/db

services:
  nginx:
    #images need to have the same name as the service, according to the subject
    image: nginx
    container_name: nginx
    build: requirements/nginx/
    restart: always
    volumes:
      - wp:/var/www/html
    networks:
      - nginxwordpress
    ports:
      - "443:443"
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    build: requirements/wordpress/
    restart: always
    volumes:
      - wp:/var/www/html
    networks:
      - nginxwordpress
      - wordpressmariadb
        #ports:
        #- "9000:9000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    build: requirements/mariadb/
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpressmariadb
        #ports:
        #- "3306:3306"
networks:
  nginxwordpress:
  wordpressmariadb:

