services:
  nginx:
    container_name: nginx
    build: nginx/
      #restart: always TODO
    volumes:
      - "/wp"
    networks:
      - nginxwordpress
    ports:
      - "443:443"
  wordpress:
    container_name: wordpress
    build: wordpress/
      #restart: always TODO
    volumes:
      - "/wp"
    networks:
      - nginxwordpress
      - wordpressmariadb
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: mariadb/
      #restart: always TODO
    volumes:
      - "/db"
    networks:
      - wordpressmariadb
networks:
  nginxwordpress:
  wordpressmariadb:
