services:
  nginx:
    container_name: nginx
    build: nginx/
  wordpress:
    container_name: wordpress
    build: wordpress/
    volumes:
      - "~/wpdb"
  mariadb:
    container_name: mariadb
    build: mariadb/
