#!/bin/sh
set -x

#echo $WP_USER_PASSWORD > /tmp/pwtest
#env > /tmp/envtest
#date >> /tmp/envtest

mysql_install_db

service mysql stop
mkdir -p /run/mysqld
chown -R mysql:mysql /run/mysqld

cat << END > /tmp/wpdbscript.sql
--this site: https://www.linode.com/docs/guides/how-to-install-wordpress-using-wp-cli-on-debian-10/ also covers this part
CREATE DATABASE IF NOT EXISTS WP;
--DROP USER IF EXISTS 'justauser'
--TODO use environment
CREATE USER 'justauser'@'%' IDENTIFIED BY '$WP_USER_PASSWORD';
--TODO use environment
CREATE USER 'boss'@'%' IDENTIFIED BY '$WP_BOSS_PASSWORD';
--https://stackoverflow.com/questions/1559955/host-xxx-xx-xxx-xxx-is-not-allowed-to-connect-to-this-mysql-server
GRANT ALL PRIVILEGES ON *.* TO 'justauser'@'%' WITH GRANT OPTION; --probably don't want to give this one all privileges
GRANT ALL PRIVILEGES ON *.* TO 'boss'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
END

cat /tmp/wpdbscript.sql

service mysql start && mysql < /tmp/wpdbscript.sql
service mysql stop
mysqld
#cat /var/log/mysql/error.log

#service mysql restart

#env
#bash

#cat /var/log/mysql/error.log

