CREATE DATABASE IF NOT EXISTS WP;
--DROP USER IF EXISTS 'justauser'
--TODO use environment
CREATE USER 'justauser' IDENTIFIED BY WP_USER_PASSWORD
--TODO use environment
CREATE USER 'boss' IDENTIFIED BY WP_BOSS_PASSWORD
GRANT ALL PRIVILEGES ON WP.* TO 'boss';
